'use strict';

const { CLUSTER } = require('zigbee-clusters');

const { mapValueRange } = require('../../../util');

const UP_OPEN = 'upOpen';
const DOWN_CLOSE = 'downClose';

/**
 * Cluster capability configuration for `windowcoverings_set`.
 * @type {ClusterCapabilityConfiguration}
 */
module.exports = {
  getOpts: {
    getOnStart: true,
  },
  get: 'currentPositionLiftPercentage',
  set: 'goToLiftPercentage',
  /**
   * @param {number} value
   * @returns {Promise<null|{percentageliftvalue: number}>}
   */
  async setParser(value) {
    // This boolean can be used to determine if incoming report are generated by a set command
    // by Homey or externally
    this._reportDebounceEnabled = true;

    // Override goToLiftPercentage to enforce blind to open/close completely
    if (value === 0 || value === 1) {
      this.debug(`set → \`windowcoverings_set\`: ${value} → setParser → ${value === 1 ? UP_OPEN : DOWN_CLOSE}`);

      await this.zclNode.endpoints[this.getClusterEndpoint(CLUSTER.WINDOW_COVERING)]
        .clusters.windowCovering[value === 1 ? UP_OPEN : DOWN_CLOSE]();
      await this.setCapabilityValue('windowcoverings_set', value);
      return null;
    }
    const mappedValue = mapValueRange(0, 1, 100, 0, value);
    const gotToLiftPercentageCommand = {
      // Round, otherwise might not be accepted by device
      percentageliftvalue: Math.round(mappedValue),
    };
    this.debug(`set → \`windowcoverings_set\`: ${value} → setParser → goToLiftPercentage`, gotToLiftPercentageCommand);
    // Send goToLiftPercentage command
    return gotToLiftPercentageCommand;
  },
  report: 'currentPositionLiftPercentage',
  /**
   * @param {number} value
   * @returns {null|number}
   */
  reportParser(value) {
    // eslint-disable-next-line no-shadow,no-constant-condition
    if (value => 0 && value <= 100) {
      const result = mapValueRange(0, 100, 1, 0, value);
      this.debug(`\`windowcoverings_set\` → reportParser → currentPositionLiftPercentage: ${value} → parsed:`, result);
      return result;
    }
    return null;
  },
};
